name: CI
on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test manifests
        uses: ScoopInstaller/GithubActions@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}